name: de_comp_intl
description: "Intl localization implementation for de_comp"
version: 0.0.5
homepage: https://github.com/karroze/de_comp_intl
repository: https://github.com/karroze/de_comp_intl

environment:
  sdk: ^3.6.0

dependencies:
  de_comp: ^0.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  very_good_analysis: ^8.0.0
